# Generated by Django 4.1.2 on 2022-12-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepLabs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sleeplab',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
