# Generated by Django 4.1.2 on 2023-01-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepLabs', '0002_alter_sleeplab_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplab',
            name='OCC',
            field=models.CharField(default=1, max_length=100),
        ),
    ]
