# Generated by Django 4.1.2 on 2023-03-13 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SleepLabs', '0003_sleeplab_occ'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sleeplab',
            options={'ordering': ('timestamp',)},
        ),
    ]
