# Generated by Django 4.1.2 on 2023-03-25 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepLabs', '0004_alter_sleeplab_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleeplab',
            name='DevID',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
