# Generated by Django 3.1.4 on 2023-05-03 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SleepLabs', '0005_sleeplab_devid'),
    ]

    operations = [
        migrations.CreateModel(
            name='SleepLabOptv1',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(default='01 June, 2022', max_length=122)),
                ('jsonData', models.JSONField(default=list)),
                ('DevID', models.CharField(default='None', max_length=20)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='SleepLabOptv1Dummy',
            fields=[
                ('auto_increment_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(default='01 June, 2022', max_length=122)),
                ('jsonData', models.JSONField(default=list)),
                ('DevID', models.CharField(default='None', max_length=20)),
            ],
            options={
                'ordering': ('-timestamp',),
            },
        ),
        migrations.AlterModelOptions(
            name='sleeplab',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='sleeplab',
            name='hrs',
            field=models.CharField(default='01 June, 2022', max_length=122),
        ),
        migrations.AddField(
            model_name='sleeplab',
            name='jsonData',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='sleeplab',
            name='min',
            field=models.CharField(default='01 June, 2022', max_length=122),
        ),
        migrations.AlterField(
            model_name='sleeplab',
            name='timestamp',
            field=models.CharField(default='01 June, 2022', max_length=122),
        ),
    ]
